title: <p align="center"> Nisha Chandora </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nishachandora0611/">LinkedIn</a> |
  <a href="https://github.com/NishaChandora">GitHub</a>
  
  <br>   
  I have 10 years of rich experience in US International Tax.
  I am currently exploring the world of AI and ML through a PG Program.
  <br>
  </p>



theme: jekyll-theme-minimal
